// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceoflcktscennfmmdrvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlb2ZsY2t0c2Nlbm5mbW1kcnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDYyOTksImV4cCI6MjA1OTUyMjI5OX0.zopyN4ImWvZ-i6JJjjW0mCc0n3IQtAbmniQ1rstwJFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);